### ISSUE TITLE
Unknown error on model H6159

### ISSUE THREAD

**Issue by codetutorIT** [nbuenger/ioBroker.govee#1]
I couldn't add my device (model: H6159). It results in an error (see below) without giving further details.

```
govee.0 | 2021-07-19 18:47:16.644 | error | (6016) H6159
-- | -- | -- | --
```

If you need any further details, i can provide them if you tell me what you need.

**Versions:**  
 - Adapter version: 0.0.5
 - JS-Controller version: 3.2.16
 - Node version: 12.22.2
 - OS: Raspbian Buster

**Comment by nbuenger** [comment]
Hey Christian,
is it correct that you got only this error line?
Is it possible That you can enable the expert log end send me the full log. 
I am convinced that we will find a solution to your problem.

**Comment by codetutorIT** [comment]
Expert log was enabled and this was the only error line.
After 2 hours the device is working. I don't know why, but the issue can be closed.

I will reopen if the problem occurs again and i can provide further details.
