### ISSUE TITLE
Neues lokales API

### ISSUE THREAD

**Issue by DEV2DEV-DE** [nbuenger/ioBroker.govee#15]
Seit kurzem unterstützt Govee auch den rein lokalen Zugriff:
![image](https://user-images.githubusercontent.com/95883579/183618706-202a5195-06da-4404-9ebf-b2d6f1cfe4d9.png)

**Comment by nbuenger** [comment]
Hey @DEV2DEV-DE,
ich habe mir die lokale API bereits angesehen.
Ich arbeite gerade daran das diese in der neuen Adapter Version vollumfänglich zur Verfügung stehen wird.
Ich brauche nur leider noch ewas.

VG Nick
