### ISSUE TITLE
Question: Is this adapter still maintained?

### ISSUE THREAD

**Issue by mcm1957** [nbuenger/ioBroker.govee#16]
Please let us (ioBroker community) know whether this adapter is still maintained and developed.

If you do not have any longer time to spend or interrest at this adapter, please let us know whether you are willing to move ownership the repo and especially the npm rights to iobroker-community

Thanks

**Comment by nickb-skutix** [comment]
Hey, ich hatte leider keine Zeit mich um den Adapter zu kümmern. Ich habe mich aber daran gesetzt eine bessere Version zu veröffentlichen. 
Es wird noch ein wenig Zeit in Anspruch nehmen. Aber die neue Version wird kommen.

**Comment by nbuenger** [comment]
Hey,
ich hatte leider wirklich keine zeit den Adapter weiter zu entwickeln.
Allerdings arbeite ich derzeit an einer neuen Version.
Es wird noch ein wenig Zeit in Anspruch nehmen.
Ich werde so bald wie möglich neue Infos mitteilen.
Tut mir sehr leid das Ihr warten musstet.

VG Nick

**Comment by mcm1957** [comment]
Danke für die überaus rasche Rückmeldung.
Ich setzet das Issue in adapter-requests mal auf work-in-progress.

Bitte überleg auch den Adapter in die offiziellen Repos aufnehmen zu lassen sobald er funktioniert.
Falls nicht bekannt, es gibt auch eine Telegramm Gruppe (oder besser 2) falls Support gewünscht ist oder Fragen zur Integration in die Repos auftauchen.

https://t.me/ioBroker_development oder
https://t.me/+gsX-e8k4mLtmZjZk (IoBroker development starters)

Martin
