### ISSUE TITLE
Dont Work :-(

### ISSUE THREAD

**Issue by tommyMX** [nbuenger/ioBroker.govee#17]
<img width="1632" alt="Bildschirm­foto 2022-11-16 um 11 31 32" src="https://user-images.githubusercontent.com/36209886/202158588-b006d120-a1f6-4dcd-ac5d-594f628e12e6.png">

**Comment by nbuenger** [comment]
Hey @tommyMX,
I am aware of the problems with the adapter.
Unfortunately I haven't had time to fix this yet.
I am currently working on a new version.

Best regards
Nick
