### ISSUE TITLE
Wird dieser Adapter noch weiter Entwickelt?

### ISSUE THREAD

**Issue by peoples0815** [nbuenger/ioBroker.govee#18]
Hallo,

ich finde bspw. die Ambilight - Lösungen von Govee super und wollte diesen Adapter installieren um diese zu steuern, leider ist er schon so alt dass er nicht mehr funktioniert.

Deshalb hier die Frage ob er noch gepflegt wird, oder das Thema hier beendet ist.

**Comment by nbuenger** [comment]
Hey,
ich arbeite gerade an einen neuen Version. Es wird noch ein klein wenig dauern bis ich damit fertig bin. 

Aber ja der Adapter bekommt bald ein Update. 

VG Nick
