### ISSUE TITLE
AxiosError

### ISSUE THREAD

**Issue by Instanz1** [nbuenger/ioBroker.govee#19]
Hallo,

ich habe jetzt immer wieder beobachtet das mir der Adapter den Log voll knallt mit dem Error:

<html><body>

govee.0 | 2022-12-12 17:51:10.510 | error | AxiosError: Request failed with status code 429
-- | -- | -- | --
govee.0 | 2022-12-12 17:51:10.141 | info | check group user admin group admin: false
govee.0 | 2022-12-12 17:51:10.139 | info | check user admin pw iobroker: false,system.user.admin
govee.0 | 2022-12-12 17:51:10.056 | info | Govee API Key: bliblablabalablabla
govee.0 | 2022-12-12 17:51:10.056 | warn | Private mode is disabled (senstive data will shown in log output)
govee.0 | 2022-12-12 17:51:10.055 | warn | Expert log disabled
govee.0 | 2022-12-12 17:51:10.045 | info | starting.  Version 0.0.6 (non-npm:  nbuenger/ioBroker.govee#73ec80b6350890015d95428dd3bbd3f72417a073) in  /opt/iobroker/node_modules/iobroker.govee, node: v16.18.1,  js-controller: 4.0.23
govee.0 | 2022-12-12 17:51:06.377 | info | Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
govee.0 | 2022-12-12 17:51:06.377 | info | terminating
govee.0 | 2022-12-12 17:51:06.376 | info | Got terminate signal TERMINATE_YOURSELF

</body>
</html>

**Comment by nbuenger** [comment]
Moin,
der errorcode 429 besagt das du zu viele Requests gemacht hast. 
Laut den Beschränkungen der Govee API sind nicht mehr als 10000 Request pro Tag mit dem selben API Key möglich. Außerdem können Pro Minute Pro Gerät nicht mehr als 10 Request gestellt werden. 

Ich arbeite aber an einer neuen Version der den Log nicht voll mit Fehlern haut. 

Solange bis die Version Fertig ist empfehle ich dir den Refresh Intervall höher zu stellen. 

VG Nick
